# Generated by Django 2.2 on 2021-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openiduser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openidprovider',
            name='signing_alg',
            field=models.CharField(choices=[('RS256', 'RS256'), ('HS256', 'HS256')], default='HS256', max_length=5),
        ),
    ]
